export const COUNTRIES: { code: string; flag: string; name: string }[] = [
  { code: "AF", flag: "🇦🇫", name: "Afghanistan" },
  { code: "AL", flag: "🇦🇱", name: "Albania" },
  { code: "DZ", flag: "🇩🇿", name: "Algeria" },
  { code: "AR", flag: "🇦🇷", name: "Argentina" },
  { code: "AU", flag: "🇦🇺", name: "Australia" },
  { code: "AT", flag: "🇦🇹", name: "Austria" },
  { code: "BD", flag: "🇧🇩", name: "Bangladesh" },
  { code: "BE", flag: "🇧🇪", name: "Belgium" },
  { code: "BR", flag: "🇧🇷", name: "Brazil" },
  { code: "BG", flag: "🇧🇬", name: "Bulgaria" },
  { code: "CA", flag: "🇨🇦", name: "Canada" },
  { code: "CL", flag: "🇨🇱", name: "Chile" },
  { code: "CN", flag: "🇨🇳", name: "China" },
  { code: "CO", flag: "🇨🇴", name: "Colombia" },
  { code: "HR", flag: "🇭🇷", name: "Croatia" },
  { code: "CZ", flag: "🇨🇿", name: "Czechia" },
  { code: "DK", flag: "🇩🇰", name: "Denmark" },
  { code: "EG", flag: "🇪🇬", name: "Egypt" },
  { code: "EE", flag: "🇪🇪", name: "Estonia" },
  { code: "FI", flag: "🇫🇮", name: "Finland" },
  { code: "FR", flag: "🇫🇷", name: "France" },
  { code: "DE", flag: "🇩🇪", name: "Germany" },
  { code: "GR", flag: "🇬🇷", name: "Greece" },
  { code: "HK", flag: "🇭🇰", name: "Hong Kong" },
  { code: "HU", flag: "🇭🇺", name: "Hungary" },
  { code: "IS", flag: "🇮🇸", name: "Iceland" },
  { code: "IN", flag: "🇮🇳", name: "India" },
  { code: "ID", flag: "🇮🇩", name: "Indonesia" },
  { code: "IR", flag: "🇮🇷", name: "Iran" },
  { code: "IQ", flag: "🇮🇶", name: "Iraq" },
  { code: "IE", flag: "🇮🇪", name: "Ireland" },
  { code: "IL", flag: "🇮🇱", name: "Israel" },
  { code: "IT", flag: "🇮🇹", name: "Italy" },
  { code: "JP", flag: "🇯🇵", name: "Japan" },
  { code: "KZ", flag: "🇰🇿", name: "Kazakhstan" },
  { code: "KE", flag: "🇰🇪", name: "Kenya" },
  { code: "KR", flag: "🇰🇷", name: "South Korea" },
  { code: "LV", flag: "🇱🇻", name: "Latvia" },
  { code: "LT", flag: "🇱🇹", name: "Lithuania" },
  { code: "MY", flag: "🇲🇾", name: "Malaysia" },
  { code: "MX", flag: "🇲🇽", name: "Mexico" },
  { code: "MA", flag: "🇲🇦", name: "Morocco" },
  { code: "NL", flag: "🇳🇱", name: "Netherlands" },
  { code: "NZ", flag: "🇳🇿", name: "New Zealand" },
  { code: "NG", flag: "🇳🇬", name: "Nigeria" },
  { code: "NO", flag: "🇳🇴", name: "Norway" },
  { code: "PK", flag: "🇵🇰", name: "Pakistan" },
  { code: "PE", flag: "🇵🇪", name: "Peru" },
  { code: "PH", flag: "🇵🇭", name: "Philippines" },
  { code: "PL", flag: "🇵🇱", name: "Poland" },
  { code: "PT", flag: "🇵🇹", name: "Portugal" },
  { code: "RO", flag: "🇷🇴", name: "Romania" },
  { code: "RU", flag: "🇷🇺", name: "Russia" },
  { code: "SA", flag: "🇸🇦", name: "Saudi Arabia" },
  { code: "RS", flag: "🇷🇸", name: "Serbia" },
  { code: "SG", flag: "🇸🇬", name: "Singapore" },
  { code: "SK", flag: "🇸🇰", name: "Slovakia" },
  { code: "ZA", flag: "🇿🇦", name: "South Africa" },
  { code: "ES", flag: "🇪🇸", name: "Spain" },
  { code: "SE", flag: "🇸🇪", name: "Sweden" },
  { code: "CH", flag: "🇨🇭", name: "Switzerland" },
  { code: "TW", flag: "🇹🇼", name: "Taiwan" },
  { code: "TH", flag: "🇹🇭", name: "Thailand" },
  { code: "TR", flag: "🇹🇷", name: "Turkey" },
  { code: "UA", flag: "🇺🇦", name: "Ukraine" },
  { code: "AE", flag: "🇦🇪", name: "UAE" },
  { code: "GB", flag: "🇬🇧", name: "United Kingdom" },
  { code: "US", flag: "🇺🇸", name: "United States" },
  { code: "VN", flag: "🇻🇳", name: "Vietnam" },
];

export const COUNTRY_MAP = Object.fromEntries(COUNTRIES.map((c) => [c.code, c]));
